
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async userGetOne() : Promise<Result<User | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_get_one") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async userSetOne(user: User) : Promise<Result<User, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_set_one", { user }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async userPreferencesGet(args: UserPreferencesGetArgs) : Promise<Result<UserPreferences | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_preferences_get", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startGoogleSignIn() : Promise<Result<GoogleAuthEventPayload, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_google_sign_in") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startEnterpriseOidcSignIn(gatewayUrl: string, providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_enterprise_oidc_sign_in", { gatewayUrl, providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async userPreferencesSet(preferences: UserPreferences) : Promise<Result<UserPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("user_preferences_set", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMicrophones() : Promise<InputDeviceDescriptor[]> {
    return await TAURI_INVOKE("list_microphones");
},
async listGpus() : Promise<GpuAdapterInfo[]> {
    return await TAURI_INVOKE("list_gpus");
},
async getScreenVisibleArea() : Promise<ScreenVisibleArea> {
    return await TAURI_INVOKE("get_screen_visible_area");
},
async getMonitorAtCursor() : Promise<MonitorAtCursor | null> {
    return await TAURI_INVOKE("get_monitor_at_cursor");
},
async checkMicrophonePermission() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_microphone_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async requestMicrophonePermission() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_microphone_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkScreenRecordingPermission() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_screen_recording_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async requestScreenRecordingPermission() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_screen_recording_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkAccessibilityPermission() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_accessibility_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async requestAccessibilityPermission() : Promise<Result<PermissionStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_accessibility_permission") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentAppInfo() : Promise<Result<CurrentAppInfoResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_app_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appTargetUpsert(args: AppTargetUpsertArgs) : Promise<Result<AppTarget, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_target_upsert", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appTargetList() : Promise<Result<AppTarget[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_target_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pairedRemoteDeviceUpsert(args: PairedRemoteDeviceUpsertArgs) : Promise<Result<PairedRemoteDevice, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paired_remote_device_upsert", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pairedRemoteDeviceList() : Promise<Result<PairedRemoteDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paired_remote_device_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pairedRemoteDeviceDelete(args: PairedRemoteDeviceDeleteArgs) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paired_remote_device_delete", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async remoteReceiverStart(args: StartRemoteReceiverArgs) : Promise<Result<RemoteReceiverStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remote_receiver_start", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async remoteReceiverStop() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remote_receiver_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async remoteReceiverStatus() : Promise<Result<RemoteReceiverStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remote_receiver_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async remoteSenderDeliverFinalText(args: RemoteSenderDeliverArgs) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remote_sender_deliver_final_text", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async remoteSenderPairWithReceiver(args: RemoteSenderPairArgs) : Promise<Result<PairedRemoteDevice, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remote_sender_pair_with_receiver", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startRecording(args: StartRecordingArgs | null) : Promise<Result<StartRecordingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_recording", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopRecording() : Promise<Result<StopRecordingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storeTranscriptionAudio(id: string, samples: number[], sampleRate: number) : Promise<Result<TranscriptionAudioSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("store_transcription_audio", { id, samples, sampleRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storageUploadData(args: StorageUploadArgs) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("storage_upload_data", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async storageGetDownloadUrl(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("storage_get_download_url", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async surfaceMainWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("surface_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPillWindowSize(size: PillWindowSize) : Promise<void> {
    await TAURI_INVOKE("set_pill_window_size", { size });
},
async paste(text: string, keybind: string | null, skipClipboardRestore: boolean | null) : Promise<Result<PasteOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paste", { text, keybind, skipClipboardRestore }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyToClipboard(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_to_clipboard", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcriptionCreate(transcription: Transcription) : Promise<Result<Transcription, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcription_create", { transcription }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcriptionList(limit: number | null, offset: number | null) : Promise<Result<Transcription[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcription_list", { limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcriptionDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcription_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcriptionUpdate(transcription: Transcription) : Promise<Result<Transcription, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcription_update", { transcription }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transcriptionAudioLoad(id: string) : Promise<Result<TranscriptionAudioData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcription_audio_load", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async purgeStaleTranscriptionAudio() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("purge_stale_transcription_audio") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportTranscription(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportDiagnostics(diagnosticsInfo: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_diagnostics", { diagnosticsInfo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termCreate(term: Term) : Promise<Result<Term, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_create", { term }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termUpdate(term: Term) : Promise<Result<Term, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_update", { term }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termList() : Promise<Result<Term[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hotkeyList() : Promise<Result<Hotkey[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hotkeySave(hotkey: Hotkey) : Promise<Result<Hotkey, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_save", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hotkeyDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrayTitle(title: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tray_title", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMenuIcon(variant: MenuIconVariant) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_menu_icon", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrayVisible(visible: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_tray_visible", { visible }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiKeyCreate(apiKey: ApiKeyCreateRequest) : Promise<Result<ApiKeyView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_key_create", { apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiKeyList() : Promise<Result<ApiKeyView[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_key_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiKeyDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_key_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async apiKeyUpdate(request: ApiKeyUpdateRequest) : Promise<Result<ApiKeyView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("api_key_update", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toneUpsert(tone: Tone) : Promise<Result<Tone, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tone_upsert", { tone }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toneList() : Promise<Result<Tone[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tone_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toneGet(id: string) : Promise<Result<Tone | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tone_get", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toneDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tone_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearLocalData() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_local_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPhase(phase: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_phase", { phase }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPillVisibility(visibility: string) : Promise<void> {
    await TAURI_INVOKE("set_pill_visibility", { visibility });
},
async notifyPillStyleInfo(count: number, name: string) : Promise<void> {
    await TAURI_INVOKE("notify_pill_style_info", { count, name });
},
async syncNativePillAssistant(payload: string) : Promise<void> {
    await TAURI_INVOKE("sync_native_pill_assistant", { payload });
},
async startKeyListener() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_key_listener") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopKeyListener() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_key_listener") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async syncHotkeyCombos(combos: string[][]) : Promise<void> {
    await TAURI_INVOKE("sync_hotkey_combos", { combos });
},
async syncCompositorHotkeys(bindings: CompositorBinding[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sync_compositor_hotkeys", { bindings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetKeyListenerState() : Promise<void> {
    await TAURI_INVOKE("reset_key_listener_state");
},
async playAudio(clip: AudioClip) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("play_audio", { clip }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTextFieldInfo() : Promise<Result<TextFieldInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_text_field_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScreenContext() : Promise<Result<ScreenContextInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_screen_context") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScreenCaptureContext() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_screen_capture_context") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedText() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_text") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gatherAccessibilityDump() : Promise<Result<AccessibilityDumpResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("gather_accessibility_dump") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFocusedFieldInfo() : Promise<Result<AccessibilityFieldInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_focused_field_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeAccessibilityFields(entries: AccessibilityWriteEntry[]) : Promise<Result<AccessibilityWriteResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_accessibility_fields", { entries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focusAccessibilityField(target: AccessibilityFocusTarget) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus_accessibility_field", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readAccessibilityFieldValues(fields: FieldValueRequest[]) : Promise<Result<FieldValueResult[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_accessibility_field_values", { fields }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enumerate currently-running processes matching `identity`. Returns every
 * candidate so the caller (which knows the binding's `windowTitle` and other
 * heuristics) can disambiguate when multiple instances are running. Returns
 * an empty vec when the app is not running.
 */
async resolveAppPids(identity: AppIdentity) : Promise<Result<AppProcessMatch[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_app_pids", { identity }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkFocusedPasteTarget() : Promise<Result<PasteTargetState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_focused_paste_target") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * - macOS:  ~/Library/Application Support/com.voquill.desktop/enterprise.json
 * - Linux:  ~/.config/com.voquill.desktop/enterprise.json
 * - Windows: C:\Users\<User>\AppData\Roaming\com.voquill.desktop\enterprise.json
 */
async readEnterpriseTarget() : Promise<Result<[string, string | null], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_enterprise_target") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runTerminalCommand(command: string) : Promise<Result<RunTerminalCommandResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_terminal_command", { command }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHotkeyStrategy() : Promise<string> {
    return await TAURI_INVOKE("get_hotkey_strategy");
},
async supportsAppDetection() : Promise<boolean> {
    return await TAURI_INVOKE("supports_app_detection");
},
async supportsPasteKeybinds() : Promise<PasteKeybindSupport> {
    return await TAURI_INVOKE("supports_paste_keybinds");
},
/**
 * Enable Java Access Bridge (JAB) for the current user by ensuring
 * `~/.accessibility.properties` opts the JVM into our assistive-tech entry.
 * 
 * JAB is what surfaces Swing/AWT components (e.g. LigoLab) to the OS-level
 * accessibility APIs our binding/import/export pipeline talks to. Without it,
 * a Java window looks like a single opaque element and we can't read or
 * write its fields.
 * 
 * Idempotent: running on an already-configured machine is a no-op. If the
 * file exists with other assistive-tech entries (e.g. screen readers), we
 * preserve them and append our value to the comma-separated list rather
 * than overwriting.
 * 
 * The JVM only reads this file at process startup, so any Java app that's
 * currently running must be restarted before the bridge is loaded.
 */
async enableJavaAccessBridge() : Promise<Result<JavaAccessBridgeStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enable_java_access_bridge") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNativeSetupStatus() : Promise<NativeSetupStatus> {
    return await TAURI_INVOKE("get_native_setup_status");
},
async runNativeSetup() : Promise<NativeSetupResult> {
    return await TAURI_INVOKE("run_native_setup");
},
async getKeyboardLanguage() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_keyboard_language") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async conversationCreate(conversation: Conversation) : Promise<Result<Conversation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_create", { conversation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async conversationList() : Promise<Result<Conversation[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async conversationUpdate(conversation: Conversation) : Promise<Result<Conversation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_update", { conversation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async conversationDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("conversation_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatMessageCreate(message: ChatMessage) : Promise<Result<ChatMessage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_message_create", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatMessageList(conversationId: string) : Promise<Result<ChatMessage[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_message_list", { conversationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatMessageUpdate(message: ChatMessage) : Promise<Result<ChatMessage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_message_update", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async chatMessageDeleteMany(ids: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("chat_message_delete_many", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns `true` when the running app bundle can be updated in-place.
 * On macOS this checks whether the process can write to the directory that
 * contains the `.app` bundle (typically `/Applications`).
 * Non-macOS platforms always return `true`.
 */
async checkAppLocationWritable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_app_location_writable") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads a `.pkg` installer to a temp directory and opens it with
 * macOS Installer.app. This is used as a fallback when the normal in-place
 * updater cannot write to the app's install location.
 */
async downloadAndOpenMacInstaller(url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_and_open_mac_installer", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemVolume() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_volume") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSystemVolume(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_system_volume", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authSignInWithCustomToken(customToken: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_sign_in_with_custom_token", { customToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authMintCustomToken() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_mint_custom_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authSignOut() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_sign_out") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authIsSignedIn() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_is_signed_in") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async returnToShell() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("return_to_shell") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens a draggable, always-on-top webview window pointed at the given URL
 * and returns a stable id that can be used to destroy it later. The window
 * renders any URL the platform webview can load (the same set the main
 * window can load). The window is independent of the main app window — it
 * will not be backgrounded behind other windows because of the always-on-top
 * flag.
 */
async floatingWindowCreate(args: CreateFloatingWindowArgs) : Promise<Result<FloatingWindowInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("floating_window_create", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async floatingWindowDestroy(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("floating_window_destroy", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async floatingWindowList() : Promise<Result<FloatingWindowInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("floating_window_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccessibilityDumpResult = { dump: string | null; windowTitle: string | null; processName: string | null; elementCount: number }
export type AccessibilityFieldInfo = { role: string | null; title: string | null; description: string | null; value: string | null; placeholder: string | null; appPid: number | null; appName: string | null; windowTitle: string | null; isSettable: boolean; elementIndexPath: number[]; fingerprintChain: ElementFingerprint[]; canPaste: boolean; 
/**
 * "jab" for Java Access Bridge fields, None for UIAutomation
 */
backend?: string | null; 
/**
 * Canonical string path for JAB elements. Empty for UIAutomation.
 * When present, resolvers prefer it over `element_index_path`.
 */
jabStringPath?: JabElementId[]; 
/**
 * Stable identity (exe path, bundle id, ...) captured at bind time.
 * Persisting this alongside the PID lets callers re-resolve the PID
 * after the host app restarts via `resolve_app_pids`.
 */
appIdentity?: AppIdentity | null; 
/**
 * Free-form escape hatch for future field metadata. See the matching
 * field on `ElementFingerprint` — same purpose: lets us extend the
 * payload later without shipping a new schema version.
 */
details?: string | null }
export type AccessibilityFocusTarget = { appPid: number; elementIndexPath: number[]; fingerprintChain: ElementFingerprint[] | null; backend?: string | null; jabStringPath?: JabElementId[] | null }
export type AccessibilityWriteEntry = { appPid: number; elementIndexPath: number[]; fingerprintChain: ElementFingerprint[] | null; value: string; backend?: string | null; jabWriteMethod?: JabWriteMethod; jabStringPath?: JabElementId[] | null }
export type AccessibilityWriteResult = { succeeded: number; failed: number; errors: string[] }
export type ApiKeyCreateRequest = { id: string; name: string; provider: string; key: string; baseUrl?: string | null; azureRegion?: string | null; includeV1Path?: boolean | null }
export type ApiKeyUpdateRequest = { id: string; name?: string | null; key?: string | null; transcriptionModel?: string | null; postProcessingModel?: string | null; openRouterConfig?: string | null; baseUrl?: string | null; azureRegion?: string | null; includeV1Path?: boolean | null }
export type ApiKeyView = { id: string; name: string; provider: string; createdAt: number; keySuffix?: string | null; keyFull?: string | null; transcriptionModel?: string | null; postProcessingModel?: string | null; openRouterConfig?: string | null; baseUrl?: string | null; azureRegion?: string | null; includeV1Path?: boolean | null }
/**
 * Stable, relaunch-surviving identifier for a host application. PIDs change
 * every launch; these fields do not. Populated by `get_focused_field_info`
 * at capture time, then passed to `resolve_app_pids` on subsequent sessions
 * to re-resolve the current PID.
 * 
 * Every field is optional because availability is platform-dependent and
 * bindings captured on one OS must still deserialize on another.
 */
export type AppIdentity = { 
/**
 * Windows: full absolute path to the process executable (e.g.
 * `C:\Program Files\LigoLab\LigoLab.exe`). Case-insensitive match.
 */
exePath?: string | null; 
/**
 * Windows: basename of `exe_path` (e.g. `LigoLab.exe`). Lossy fallback
 * used when the install directory differs across machines.
 */
exeName?: string | null; 
/**
 * macOS: `CFBundleIdentifier` of the application (e.g.
 * `com.ligolab.client`). The canonical stable id on that platform.
 */
bundleId?: string | null }
/**
 * A currently-running process that matches an `AppIdentity`. Returned from
 * `resolve_app_pids`; the caller (frontend) picks one, typically by
 * matching `window_title` against the title recorded with the binding.
 */
export type AppProcessMatch = { pid: number; exePath: string | null; appName: string | null; windowTitle: string | null }
export type AppTarget = { id: string; name: string; createdAt: string; toneId: string | null; iconPath: string | null; pasteKeybind?: string | null }
export type AppTargetUpsertArgs = { id: string; name: string; toneId?: string | null; iconPath?: string | null; pasteKeybind?: string | null }
export type AudioClip = "start_recording_clip" | "stop_recording_clip" | "alert_linux_clip" | "alert_macos_clip" | "alert_windows_10_clip" | "alert_windows_11_clip"
export type ChatMessage = { id: string; conversationId: string; role: string; content: string; createdAt: number; metadata: string | null }
export type CompositorBinding = { actionName: string; keys: string[] }
export type Conversation = { id: string; title: string; createdAt: number; updatedAt: number }
export type CreateFloatingWindowArgs = { url: string; title: string | null; width: number | null; height: number | null; minWidth: number | null; minHeight: number | null; x: number | null; y: number | null; decorations: boolean | null; transparent: boolean | null; resizable: boolean | null; focused: boolean | null }
export type CurrentAppInfoResponse = { appName: string; iconBase64: string }
export type ElementFingerprint = { automationId: string | null; className: string | null; controlType: number; name: string | null; frameworkId: string | null; childIndex: number; 
/**
 * macOS only. AXRole of the element at this depth (e.g. "AXTextArea").
 * Required match at resolve time when present.
 */
axRole?: string | null; 
/**
 * macOS only. AXSubrole if any (e.g. "AXSecureTextField").
 */
axSubrole?: string | null; 
/**
 * macOS only. AXTitle.
 */
axTitle?: string | null; 
/**
 * macOS only. AXDescription / AXHelp text.
 */
axDescription?: string | null; 
/**
 * macOS only. AXIdentifier (developer-assigned) when present — strongest
 * stable signal and a hard disqualifier when mismatched.
 */
axIdentifier?: string | null; 
/**
 * Free-form escape hatch for future fingerprint metadata. Persisted
 * round-trip through the frontend / Firestore so we can extend
 * fingerprinting later without bumping the type schema. Convention:
 * JSON string keyed by feature name when there's something to store.
 */
details?: string | null }
export type FieldValueRequest = { appPid: number; elementIndexPath: number[]; fingerprintChain: ElementFingerprint[] | null; backend?: string | null; jabStringPath?: JabElementId[] | null }
export type FieldValueResult = { value: string | null; error: string | null }
export type FloatingWindowInfo = { id: string; url: string; title: string }
export type GoogleAuthEventPayload = { idToken: string; accessToken: string; refreshToken: string | null; expiresIn: number; tokenType: string; user: GoogleUserInfo }
export type GoogleUserInfo = { sub: string; email: string | null; name: string | null; picture: string | null }
export type GpuAdapterInfo = { name: string; vendor: number; device: number; deviceType: string; backend: string }
export type Hotkey = { id: string; actionName: string; keys: string[] }
export type InputDeviceDescriptor = { label: string; is_default: boolean; caution: boolean }
/**
 * Canonical string identifier for a JAB element at one level of the tree.
 * JAB has no developer-assigned ID, so we combine `name` + `role` (English)
 * with `index_in_parent` as a tiebreaker when siblings collide.
 */
export type JabElementId = { name: string | null; role: string | null; indexInParent: number }
export type JabWriteMethod = 
/**
 * JAB `setTextContents` API — replaces entire field contents directly.
 */
"setTextContents" | 
/**
 * Focus element → Ctrl+A → Ctrl+V (clipboard paste). Default.
 */
"clipboardPaste" | 
/**
 * Focus element → Ctrl+A → type each character via SendInput.
 */
"keystrokeSimulation" | 
/**
 * Read current text, compute diff, apply minimal edits via cursor + keystrokes.
 */
"keystrokeSimulationSmart"
export type JavaAccessBridgeStatus = { 
/**
 * Absolute path to the `.accessibility.properties` file we operate on.
 */
path: string; 
/**
 * True if the file already contained our entry — nothing was changed.
 */
alreadyEnabled: boolean; 
/**
 * True if we wrote (or rewrote) the file.
 */
wroteFile: boolean; 
/**
 * True if any Java app currently running needs to be restarted before
 * it picks up the bridge. Always true when `wrote_file` is true.
 */
restartRequired: boolean }
export type MenuIconVariant = "default" | "update"
export type MonitorAtCursor = { x: number; y: number; width: number; height: number; visibleX: number; visibleY: number; visibleWidth: number; visibleHeight: number; scaleFactor: number; cursorX: number; cursorY: number }
export type NativeSetupResult = "success" | "require-restart" | "failed"
export type NativeSetupStatus = "ready" | "needs-setup" | "needs-restart"
export type PairedRemoteDevice = { id: string; name: string; platform: string; role: string; sharedSecret: string; pairedAt: string; lastSeenAt?: string | null; lastKnownAddress?: string | null; trusted?: boolean }
export type PairedRemoteDeviceDeleteArgs = { id: string }
export type PairedRemoteDeviceUpsertArgs = { id: string; name: string; platform: string; role: string; sharedSecret: string; pairedAt: string; lastSeenAt?: string | null; lastKnownAddress?: string | null; trusted?: boolean }
export type PasteKeybindSupport = "disabled" | "per-app" | "global"
export type PasteOutcome = "pasted" | "copied_to_clipboard"
export type PasteTargetState = "editable" | "not_editable" | "unknown"
export type PermissionKind = "microphone" | "accessibility" | "screen-recording"
export type PermissionState = "authorized" | "denied" | "restricted" | "not-determined"
export type PermissionStatus = { kind: PermissionKind; state: PermissionState; promptShown: boolean }
export type PillWindowSize = "dictation" | "assistant_compact" | "assistant_expanded" | "assistant_typing"
export type RemoteReceiverStatus = { enabled: boolean; deviceId: string; deviceName: string; listenAddress: string | null; port: number | null; pairingCode: string; lastSenderDeviceId: string | null; lastEventId: string | null; lastDeliveryStatus: string | null; lastDeliveryAt: string | null; lastError: string | null; lastTargetClassName: string | null; lastTargetTitle: string | null; lastTargetEditable: boolean | null; devicePlatform: string }
export type RemoteSenderDeliverArgs = { targetDeviceId: string; text: string; mode: string }
export type RemoteSenderPairArgs = { receiverDeviceId: string; receiverName: string; receiverPlatform: string; receiverAddress: string; pairingCode: string }
/**
 * Reads `enterprise.json` from the app config directory. Returns `None` if the file does not exist.
 * 
 * Platform paths:
 */
export type RunTerminalCommandResponse = { stdout: string; stderr: string; exitCode: number }
export type ScreenContextInfo = { screenContext: string | null }
export type ScreenVisibleArea = { topInset: number; bottomInset: number; leftInset: number; rightInset: number }
export type StartRecordingArgs = { preferredMicrophone: string | null }
export type StartRecordingResponse = { sampleRate: number }
export type StartRemoteReceiverArgs = { port?: number | null }
export type StopRecordingResponse = { samples: number[]; sampleRate: number }
export type StorageUploadArgs = { path: string; data: number[] }
export type Term = { id: string; createdAt: number; createdByUserId: string; sourceValue: string; destinationValue: string; isReplacement: boolean; isDeleted: boolean }
export type TextFieldInfo = { cursorPosition: number | null; selectionLength: number | null; textContent: string | null }
export type Tone = { id: string; name: string; promptTemplate: string; createdAt: number; sortOrder: number }
export type Transcription = { id: string; transcript: string; timestamp: number; audio?: TranscriptionAudioSnapshot | null; modelSize?: string | null; inferenceDevice?: string | null; rawTranscript?: string | null; sanitizedTranscript?: string | null; transcriptionPrompt?: string | null; postProcessPrompt?: string | null; transcriptionApiKeyId?: string | null; postProcessApiKeyId?: string | null; transcriptionMode?: string | null; postProcessMode?: string | null; postProcessDevice?: string | null; transcriptionDurationMs?: number | null; postprocessDurationMs?: number | null; warnings?: string[] | null; remoteStatus?: string | null; remoteDeviceId?: string | null }
export type TranscriptionAudioData = { samples: number[]; sampleRate: number }
export type TranscriptionAudioSnapshot = { filePath: string; durationMs: number }
export type User = { id: string; name: string; bio: string; company?: string | null; title?: string | null; onboarded: boolean; preferredMicrophone?: string | null; preferredLanguage?: string | null; wordsThisMonth?: number; wordsThisMonthMonth?: string | null; wordsTotal?: number; playInteractionChime?: boolean; hasFinishedTutorial?: boolean; hasMigratedPreferredMicrophone?: boolean; cohort?: string | null; stylingMode?: string | null; selectedToneId?: string | null; activeToneIds?: string | null; streak?: number | null; streakRecordedAt?: string | null; referralSource?: string | null }
export type UserPreferences = { userId: string; transcriptionMode?: string | null; transcriptionApiKeyId?: string | null; transcriptionDevice?: string | null; transcriptionModelSize?: string | null; postProcessingMode?: string | null; postProcessingApiKeyId?: string | null; postProcessingOllamaUrl?: string | null; postProcessingOllamaModel?: string | null; agentMode?: string | null; agentModeApiKeyId?: string | null; openclawGatewayUrl?: string | null; openclawToken?: string | null; activeToneId?: string | null; gotStartedAt?: number | null; gpuEnumerationEnabled?: boolean; pasteKeybind?: string | null; lastSeenFeature?: string | null; isEnterprise?: boolean; languageSwitchEnabled?: boolean; secondaryDictationLanguage?: string | null; activeDictationLanguage?: string | null; additionalDictationLanguages?: string[] | null; preferredMicrophone?: string | null; ignoreUpdateDialog?: boolean; incognitoModeEnabled?: boolean; incognitoModeIncludeInStats?: boolean; dictationLimitMinutes?: number; dictationPillVisibility?: string; useNewBackend?: boolean; realtimeOutputEnabled?: boolean; remoteOutputEnabled?: boolean; remoteTargetDeviceId?: string | null; remoteReceiverPort?: number | null; remoteReceiverAutoStart?: boolean; dictationAudioDim?: number; menuBarIconHidden?: boolean }
export type UserPreferencesGetArgs = { userId: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
