use desktop_lib::commands::*;
use specta_typescript::{BigIntExportBehavior, Typescript};
use tauri_specta::{collect_commands, Builder};

fn main() {
    let builder = Builder::<tauri::Wry>::new().commands(collect_commands![
        user_get_one,
        user_set_one,
        user_preferences_get,
        start_google_sign_in,
        start_enterprise_oidc_sign_in,
        user_preferences_set,
        list_microphones,
        list_gpus,
        get_screen_visible_area,
        get_monitor_at_cursor,
        check_microphone_permission,
        request_microphone_permission,
        check_screen_recording_permission,
        request_screen_recording_permission,
        check_accessibility_permission,
        request_accessibility_permission,
        get_current_app_info,
        app_target_upsert,
        app_target_list,
        paired_remote_device_upsert,
        paired_remote_device_list,
        paired_remote_device_delete,
        remote_receiver_start,
        remote_receiver_stop,
        remote_receiver_status,
        remote_sender_deliver_final_text,
        remote_sender_pair_with_receiver,
        start_recording,
        stop_recording,
        store_transcription_audio,
        storage_upload_data,
        storage_get_download_url,
        surface_main_window,
        set_pill_window_size,
        paste,
        copy_to_clipboard,
        transcription_create,
        transcription_list,
        transcription_delete,
        transcription_update,
        transcription_audio_load,
        purge_stale_transcription_audio,
        export_transcription,
        export_diagnostics,
        term_create,
        term_update,
        term_list,
        term_delete,
        hotkey_list,
        hotkey_save,
        hotkey_delete,
        set_tray_title,
        set_menu_icon,
        set_tray_visible,
        api_key_create,
        api_key_list,
        api_key_delete,
        api_key_update,
        tone_upsert,
        tone_list,
        tone_get,
        tone_delete,
        clear_local_data,
        set_phase,
        set_pill_visibility,
        notify_pill_style_info,
        sync_native_pill_assistant,
        start_key_listener,
        stop_key_listener,
        sync_hotkey_combos,
        sync_compositor_hotkeys,
        reset_key_listener_state,
        play_audio,
        get_text_field_info,
        get_screen_context,
        get_screen_capture_context,
        get_selected_text,
        gather_accessibility_dump,
        get_focused_field_info,
        write_accessibility_fields,
        focus_accessibility_field,
        read_accessibility_field_values,
        resolve_app_pids,
        check_focused_paste_target,
        read_enterprise_target,
        run_terminal_command,
        get_hotkey_strategy,
        supports_app_detection,
        supports_paste_keybinds,
        enable_java_access_bridge,
        get_native_setup_status,
        run_native_setup,
        get_keyboard_language,
        conversation_create,
        conversation_list,
        conversation_update,
        conversation_delete,
        chat_message_create,
        chat_message_list,
        chat_message_update,
        chat_message_delete_many,
        check_app_location_writable,
        download_and_open_mac_installer,
        get_system_volume,
        set_system_volume,
        auth_sign_in_with_custom_token,
        auth_mint_custom_token,
        auth_sign_out,
        auth_is_signed_in,
        return_to_shell,
        floating_window_create,
        floating_window_destroy,
        floating_window_list,
    ]);

    let manifest_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output_path = manifest_dir.join("../../../packages/desktop-native-apis/src/bindings.ts");

    builder
        .export(
            Typescript::default().bigint(BigIntExportBehavior::Number),
            &output_path,
        )
        .expect("failed to export bindings");

    println!("Bindings written to {}", output_path.display());
}
